(lang dune 3.21)
(using rocq 0.11)
(using melange 0.1)

(name rocqducers)

(package
 (allow_empty)
 (name rocqducers)
 (depends
  (ocaml (>= 5.2))
  (dune (>= 3.21))
  melange
  rocq-core
  rocq-stdlib))
